### ISSUE TITLE
Get returning bug

### ISSUE THREAD

**Issue by JayShwarze** [CSAllenISDClassroom/sudokuserver-team-2#6]
When using get when trying to return the current cells for the game, we get status code 200 OK instead of 400 bad request. We should get the bad request as the response does not return the board of cells and their indexes, instead it returns the representation of the board itself
![Capture](https://user-images.githubusercontent.com/70460192/138329041-bd0593a2-13a9-483a-8e42-0e348d7b8d23.PNG)

**Comment by reese-h** [comment]
please use the current version. fixed in current version / no longer able to replicate
